In [3]:
#載入csv檔案

# pd.read_csv() 使⽤預設參數
import pandas as pd
csv_url = "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.csv"
csv_df = pd.read_csv(csv_url)
csv_df
# pd.read_csv() ⾃⾏指定變數的名稱
import pandas as pd
csv_url = "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.csv"
csv_df = pd.read_csv(csv_url, header=None, skiprows=1, names=['number', 'player', 'pos', 'ht', 'wt', 'birth_date', 'college'])
csv_df

,number,player,pos,ht,wt,birth_date,college
0,0,Randy Brown,PG,6-2,190,"May 22, 1968","University of Houston, New Mexico State Univer..."
1,30,Jud Buechler,SF,6-6,220,"June 19, 1968",University of Arizona
2,35,Jason Caffey,PF,6-8,255,"June 12, 1973",University of Alabama
3,53,James Edwards,C,7-0,225,"November 22, 1955",University of Washington
4,54,Jack Haley,C,6-10,240,"January 27, 1964","University of California, Los Angeles"
5,9,Ron Harper,PG,6-6,185,"January 20, 1964",Miami University
6,23,Michael Jordan,SG,6-6,195,"February 17, 1963",University of North Carolina
7,25,Steve Kerr,PG,6-3,175,"September 27, 1965",University of Arizona
8,7,Toni Kukoc,SF,6-10,192,"September 18, 1968",NaN
9,13,Luc Longley,C,7-2,265,"January 19, 1969",University of New Mexico
10,33,Scottie Pippen,SF,6-8,210,"September 25, 1965",University of Central Arkansas
11,91,Dennis Rodman,PF,6-7,210,"May 13, 1961",Southeastern Oklahoma State University
12,22,John Salley,PF,6-11,230,"May 16, 1964",Georgia Institute of Technology
13,8,Dickey Simpkins,PF,6-9,248,"April 6, 1972",Providence College
14,34,Bill Wennington,C,7-0,245,"April 26, 1963",St. John's University

In [2]:
#載入txt檔案

# pd.read_table() 指定 sep=";"
import pandas as pd
txt_url = "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.txt"
txt_df = pd.read_table(txt_url, sep=";")
txt_df

,No.,Player,Pos,Ht,Wt,Birth Date,College
0,0,Randy Brown,PG,6-2,190,May 22; 1968,University of Houston; New Mexico State Univer...
1,30,Jud Buechler,SF,6-6,220,June 19; 1968,University of Arizona
2,35,Jason Caffey,PF,6-8,255,June 12; 1973,University of Alabama
3,53,James Edwards,C,7-0,225,November 22; 1955,University of Washington
4,54,Jack Haley,C,6-10,240,January 27; 1964,University of California; Los Angeles
5,9,Ron Harper,PG,6-6,185,January 20; 1964,Miami University
6,23,Michael Jordan,SG,6-6,195,February 17; 1963,University of North Carolina
7,25,Steve Kerr,PG,6-3,175,September 27; 1965,University of Arizona
8,7,Toni Kukoc,SF,6-10,192,September 18; 1968,NaN
9,13,Luc Longley,C,7-2,265,January 19; 1969,University of New Mexico
10,33,Scottie Pippen,SF,6-8,210,September 25; 1965,University of Central Arkansas
11,91,Dennis Rodman,PF,6-7,210,May 13; 1961,Southeastern Oklahoma State University
12,22,John Salley,PF,6-11,230,May 16; 1964,Georgia Institute of Technology
13,8,Dickey Simpkins,PF,6-9,248,April 6; 1972,Providence College
14,34,Bill Wennington,C,7-0,245,April 26; 1963,St. John's University

In [22]:
import math # 要使⽤圓周率 pi 得引入套件 math
def circle_calculator(r):
 '''
 輸入半徑長度可以計算出圓⾯積與圓周長
 將圓⾯積與圓周長⼀起回傳
 '''
 area = math.pi * r ** 2
 circum = 2 * math.pi * r
 return area, circum
print (circle_calculator(3))

(28.274333882308138, 18.84955592153876)